// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uirhpaagmechadccdkir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcmhwYWFnbWVjaGFkY2Nka2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzEyMTMsImV4cCI6MjA2NjYwNzIxM30._L_9h715dH6r4STa5l8zJJ3tSEw1ckxfb9smH33pXkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);